// Where every verse lies on its page(s): the areas of its Arabic text and of
// its translation, as fractions of the PDF page. The data is generated by
// tools/build-regions.mjs into one file per juz (data/regions/juz-N.json)
// and loaded only when a page of that juz is shown.

/**
 * @typedef {[number, number, number, number]} Area  x, y, width, height (0..1 of the page, y from the top)
 * @typedef {{pdfPage: number, surah: number, ayah: number, arabic: Area[], translation: Area[], areas: Area[]}} VerseRegion
 */

/** @type {Map<number, VerseRegion[]>} */
const byPage = new Map();
/** @type {Map<number, Promise<void>>} */
const loading = new Map();

export const VerseRegions = {
  /** Regions on a page (numbered through the PDF files); empty until its juz is loaded. */
  onPage(pdfPage) {
    return byPage.get(pdfPage) || [];
  },

  /** Load the regions of a juz (1..30). Resolves when they are available. */
  load(juz) {
    if (!loading.has(juz)) {
      loading.set(juz, fetch(`./data/regions/juz-${juz}.json`)
        .then((res) => (res.ok ? res.json() : {}))
        .then((pages) => {
          for (const [page, verses] of Object.entries(pages)) {
            const pdfPage = Number(page);
            byPage.set(pdfPage, verses.map(([surah, ayah, arabic, translation]) => ({
              pdfPage, surah, ayah, arabic, translation, areas: [...arabic, ...translation]
            })));
          }
        })
        .catch((err) => {
          console.error(err);
          loading.delete(juz);
        }));
    }
    return loading.get(juz);
  }
};
